### ISSUE TITLE
boot2docker url not working

### ISSUE THREAD

**Issue by JakeChampion** [jkbrzt/cloudtunes#31]
Hi,

I've followed the instructions in the readme to build the image and run it as a container, all of that went well.

I have an issue where when running the container, I cannot view the web application in my browser.

Boot2Docker reports `192.168.59.103` as my IP, when using this IP with the port specified in the readme `8000` I get a page not found error message from the browser.

Is there anyway to debug this on my side at all?

**Comment by gregman4** [comment]
Did you ever resolve this issue? I seem to be in a similar situation. Running on EC2 everything in the installation looked like ti went well. But when I visit <my ip>:8000 my browser says that theres nothing there.

**Comment by JakeChampion** [comment]
I didn't resolve the issue, I chose to give up. I wish you the best of luck!
