### ISSUE TITLE
Missing local.py file.

### ISSUE THREAD

**Issue by kenetik** [jkbrzt/cloudtunes#32]
During the docker img build.

    Step 24 : ADD cloudtunes-server/cloudtunes/settings/local.py /home/cloudtunes/cloudtunes-server/cloudtunes/settings/local.py
    INFO[0000] cloudtunes-server/cloudtunes/settings/local.py: no such file or directory

**Comment by gregman4** [comment]
I have not had that specific issue, but I have been unsuccessfully trying to set this up in EC2. Please let me know if you do get it going because I would love to figure out how I finally get cloudtines working. 
Thanks.

**Comment by acjay** [comment]
Same problem here, following the Docker instructions. I assume something in the image script is supposed to create this file?

**Comment by jkbrzt** [comment]
Please see step 2 in the installation instructions:

https://github.com/jkbrzt/cloudtunes#installation
